### ISSUE TITLE
Demo User

### ISSUE THREAD

**Issue by IrinaAmzashvili** [IrinaAmzashvili/honeycomb#6]
* As an unregistered and unauthorized user I would like to easily find a button in the navbar to allow me to visit the site as a guest without signing up or logging in.
    * While on the splash page of the site:
        * I can click on Demo User button to log in and access the site as a normal user.
            * So that I can test the site without entering any credentials.

**Comment by Machaelmus** [comment]
Rough styling applied, will need proper styling to the buttons
